### ISSUE TITLE
ios11 beta error

### ISSUE THREAD

**Issue by xiongjianxu** [RNCryptor/RNCryptor-objc#17]
In the ios11 beta version, will report the following error: Conflicting types for 'SecRandomCopyBytes'
How can i solve it?

**Comment by xiongjianxu** [comment]
before ios11 beta : `int SecRandomCopyBytes(SecRandomRef __nullable rnd, size_t count, uint8_t *bytes)`
in ios11 beta : `int SecRandomCopyBytes(SecRandomRef __nullable rnd, size_t count, void *bytes)`

the `bytes`'s type has changed.

**Comment by blolo** [comment]
I have same exact issue which is concerning 
 RNCryptor.m:61:12: Conflicting types for 'SecRandomCopyBytes'

is there going to be a  3.0.3 that has a fix for this issue ?

**Comment by niveus** [comment]
I submitted PR #16 for this. I don't think the signature definition is needed anymore so I removed it. It may have been there for older versions of MacOS

**Comment by mbm29414** [comment]
Any idea when this might be pushed? I can't run my app on Xcode 9 because of this error. I tried cloning the repo and making the suggested update myself, but then couldn't figure out how to get the framework loaded manually into my app. I kept getting other errors that way (specifically a "file not found" when looking for RNCryptor.h in RNCryptorEngine.h). Anyway, I'd like to be able to have the option to move to Xcode 9 and implement wireless debugging, so if you could update the Cocoapod, that would be great! Thanks!

**Comment by rnapier** [comment]
Fixed a slightly different way. I don't want to lose 10.6 support; it's for a specific team. Thanks for the PR.

**Comment by Venkat1128** [comment]
Hi ,
I have same exact issue which is concerning
RNCryptor.m:61:12: Conflicting types for 'SecRandomCopyBytes'
I am using pod 'RNCryptor-objc' .
My App is crashing becasue fo this issue .
Please let me know when do we have fix for this.

Thanks,
Venkat

**Comment by tysun** [comment]
Anyone find a fix for this yet? It's the single error in my project 😨

**Comment by rnapier** [comment]
@Venkat1128 
This should be fixed in 3.0.5. Line 61 is now a comment, so this error can't be from the latest build.

**Comment by Venkat1128** [comment]
Thanks @rnapier Its working fine .
sorry for late reply.
