### ISSUE TITLE
Decrypting File Encrypted with OpenSSL

### ISSUE THREAD

**Issue by ghost** [RNCryptor/RNCryptor-objc#22]
Hi Rob.

Enjoying your encryption framework. But with the latest release it appears you have removed the RNOpenSSL encrypt and decrypt files.

I was unable to decrypt a file encrypted via terminal with OpenSSL. I tried the Basic Objective-C Usage in your documentation.

Is it still possible to use openssl with the latest RNCryptor version?

/Philip Borges

**Comment by rnapier** [comment]
See https://github.com/rnapier/RNOpenSSLCryptor. I don't support that code any more, but it's still available.

**Comment by useresu** [comment]
Quick question. I need to encrypt a lot of files and decrypt them on the fly in iOS app. So I planned to encrypt them by batch terminal process and then have my app decrypt them. With openssl solution it was obvious to use. How would I go about using your latest RNCryptor? What way do you suggest I should encrypt the files so I can decrypt them with your lib?
Thanks for your help!

**Comment by rnapier** [comment]
@useresu I'd recommend building a command line tool using whichever language is convenient. I don't believe anyone has built a general-purpose commandline tool, but they're pretty easy to build:

* https://github.com/RNCryptor/RNCryptor/tree/master/Examples/rncrypt
* https://github.com/RNCryptor/RNCryptor-objc/tree/master/rncrypt

[Python](https://github.com/RNCryptor/RNCryptor-objc/tree/master/rncrypt) is also pretty easy to adapt to a commandline tool. I usually build them ad hoc rather than having a general tool, but I'd certainly merge a simple unix tool that handled it.

**Comment by useresu** [comment]
Thanks, I will follow that advice.
