### ISSUE TITLE
Use of banned api in library

### ISSUE THREAD

**Issue by Gautam-zodape** [RNCryptor/RNCryptor-objc#41]
I have run the penetrating security test on the iOS app found issue with RNEncryptor library.
pen test error : The binary may contain the following insecure API(s).

Following are the classes which used insecure api methods (memcpy)-
- RNCryptor.m (Line number 242, 275, 279, 282)

Could you provide a solution for this?
Please suggest if you have any alternative for it.

**Comment by rnapier** [comment]
The code you're referencing is copied directly from Apple's [CommonCrypto](http://opensource.apple.com/source/CommonCrypto/CommonCrypto-55010/Source/API/CommonKeyDerivation.c) in order to support OS X 10.6. It is not called on any platform after that (OS X 10.7 or any version of iOS).

This code is secure. If you are aware of a vulnerability in this library, I will absolutely fix that. But your scanner is not looking for actual vulnerabilities. It's looking for text strings.

What function do you think should be used rather than memcpy? If you send a PR that maintains 10.6 support, I will look it at, but I believe your scanner is wrong. I expect it's built for Windows and doesn't understand other platforms. It probably recommends using memcpy_s instead, which is a Windows-specific function. (Changing this well-audited code from Apple to use another function also likely creates more security risk than it solves, so I'd need to review any proposed change very carefully.)

If you want to fork RNCryptor for your own use and remove 10.6 support, you're free to do so of course. But I would recommend finding a better scanner instead. 

Or if you'll submit a PR, I'd be happy to look at it.
